export const Types = {
  GET_ERRORS: 'GET_ERRORS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_DARK_THEME: 'SET_DARK_THEME',
  SET_LIGHT_THEME: 'SET_LIGHT_THEME',
  SET_TODOS: 'SET_TODOS',
  CREATE_TODO: 'CREATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  SET_CATEGORIES: 'SET_CATEGORIES',
  CREATE_CATEGORY: 'ADD_CATEGORY',
  SET_FILTER: 'SET_FILTER',
  SET_FILTER_CATEGORY: 'SET_FILTER_CATEGORY',
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION'
}

export const Filters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_DONE: 'SHOW_DONE',
  SHOW_UNDONE: 'SHOW_UNDONE',
  SHOW_DUE_SOON: 'SHOW_DUE_SOON',
  SHOW_BY_CATEGORY: 'SHOW_BY_CATEGORY'
}
