export const Types = Object.freeze({
  SET_USER: 'SET_USER',

  SET_DARK_THEME: 'SET_DARK_THEME',
  SET_LIGHT_THEME: 'SET_LIGHT_THEME',

  SET_TODOS: 'SET_TODOS',
  CREATE_TODO: 'CREATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',

  SET_CATEGORIES: 'SET_CATEGORIES',
  CREATE_CATEGORY: 'ADD_CATEGORY',

  SET_FILTER: 'SET_FILTER',
  SET_CATEGORY_FILTER: 'SET_CATEGORY_FILTER',
  SET_DATE_FILTER: 'SET_DATE_FILTER'
})
